import Navbar from "@/Components/Navbar";
import "./globals.css";
import { Nunito, Comfortaa } from "next/font/google";
import Footer from "@/Components/Footer";
import AuthProvider from "@/Provider/AuthProvider";
import { Toaster } from "react-hot-toast";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const comfortaa = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} ${comfortaa.variable} antialiased`}>
        <AuthProvider>
          <Navbar></Navbar>
          <div className="min-h-screen">{children}</div>
          <Footer></Footer>
          <Toaster></Toaster>
        </AuthProvider>
      </body>
    </html>
  );
}
